version: "3.1"
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: usersDB
      MYSQL_PASSWORD: example
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./conf:/etc/mysql/conf.d
      - persistent:/var/lib/mysql
    networks:
      - default
  www:
    build: .
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./www:/var/www/html
      - ./apache-config.conf:/etc/apache2/conf-available/my-apache.conf
      - /etc/nginx:/etc/nginx  # Monta el directorio de configuración de NGINX  
      - /etc/nginx/certificate.crt  # Ruta al archivo de certificado
      - /etc/nginx/private.key  #Ruta a la llave privada
    links:
      - db
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: example
      MYSQL_ROOT_PASSWORD: example
volumes:
  persistent:

networks:
  default:
